In [3]:
import pandas as pd
import numpy as np


In [4]:
data = pd.read_csv("train.csv")

In [5]:
data.head()

id  A      B       C  D  E   F  G      H  I  J   K  L  M      N    O  P
0   1  b  18.42  10.415  y  p  aa  v  0.125  t  f   0  f  g  120.0  375  1
1   2  a  21.75  11.750  u  g   c  v  0.250  f  f   0  t  g  180.0    0  1
2   3  b  30.17   1.085  y  p   c  v  0.040  f  f   0  f  g  170.0  179  1
3   4  b  22.67   2.540  y  p   c  h  2.585  t  f   0  f  g    0.0    0  0
4   5  a  36.00   1.000  u  g   c  v  2.000  t  t  11  f  g    0.0  456  0

In [10]:
data.J.value_counts()

f    319
t    233
Name: J, dtype: int64

In [6]:
data.B.describe()

count    543.000000
mean      31.364899
std       11.873665
min       13.750000
25%       22.500000
50%       28.170000
75%       37.665000
max       80.250000
Name: B, dtype: float64

28.17

In [11]:
data.I.value_counts()

t    286
f    266
Name: I, dtype: int64

In [12]:
data.isnull().sum()

id     0
A      8
B      9
C      0
D      5
E      5
F      7
G      7
H      0
I      0
J      0
K      0
L      0
M      0
N     11
O      0
P      0
dtype: int64

In [1]:
data.B.describe()

NameError: name 'data' is not defined

In [3]:
data.drop(['D','J'],axis =1,inplace =True)

In [4]:
data.columns

Index([u'id', u'A', u'B', u'C', u'E', u'F', u'G', u'H', u'I', u'K', u'L', u'M',
       u'N', u'O', u'P'],
      dtype='object')

In [ ]:
#data.columns
#B1 = data.B
#B1.dropna(inplace=True)
#b_med = B1.median()

In [ ]:
#N1 = data.N
#N1.dropna(inplace=True)
#n_med = N1.median()

In [ ]:
data.G.value_counts()

In [5]:

##replace 
data.B.fillna(28.17,inplace = True)
data.N.fillna(152,inplace = True)


In [ ]:
#data.A.fillna('b',inplace = True)
#data.E.fillna('g',inplace = True)
#data.F.fillna('c',inplace = True)
#data.G.fillna('v',inplace = True)

In [6]:
data.fillna('NN',inplace = True)

In [7]:
target = data.P
data.drop('P', axis =1, inplace = True)

In [29]:
data_int = data.select_dtypes(include=['float64','int64']).copy()
data_int.head()
data_cat = data.select_dtypes(include=['object']).copy()
data_cat.head()

A  E   F  G  I  L  M
0  b  p  aa  v  t  f  g
1  a  g   c  v  f  t  g
2  b  p   c  v  f  f  g
3  b  p   c  h  t  f  g
4  a  g   c  v  t  f  g

In [18]:
data_int = data.select_dtypes(include=['float64','int64']).copy()
data_int.head()
data_cat = data.select_dtypes(include=['object']).copy()
data_int.head()
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encod = LabelEncoder()

data_cat_le = data_cat.apply(label_encod.fit_transform)

one_he = OneHotEncoder()
data_X =one_he.fit_transform(data_cat_le)
data_X =data_X.toarray()

In [47]:
data_int = data.select_dtypes(include=['float64','int64']).copy()
#data_int.head()
data_cat = data.select_dtypes(include=['object']).copy()
#data_int.head()
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encod = LabelEncoder()
one_he = OneHotEncoder()

data_cat_le = data_cat.apply(label_encod.fit_transform)
data_X =one_he.fit_transform(data_cat_le)
data_X =data_X.toarray()
data_int = data_int.as_matrix()
X = np.concatenate((data_int[:,1::],data_X ), axis=1)
Y=target

In [ ]:
train_X = tra
#data.drop('J', axis =1, inplace = True)

In [ ]:
data_set_one_hot = pd.get_dummies(data)

In [ ]:
data_set_one_hot.shape

In [ ]:
data_set_one_hot.columns

In [ ]:
data_X = data_set_one_hot.as_matrix()
#X = data_X[:,1:data_set_one_hot.shape[1]]
X = data_X
Y = target.as_matrix()

In [ ]:
X.shape

In [49]:
from sklearn.model_selection import train_test_split
seed = 10
test_size = 0.3
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=seed)
#X_train = X_train_al[:,1:data_set_one_hot.shape[1]]
#X_test = X_test_al[:,1:data_set_one_hot.shape[1]]

In [ ]:
len(X_test_al)

In [50]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from xgboost import plot_tree
import pandas as pd



from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import  f1_score
%matplotlib inline

In [51]:
model = XGBClassifier(booster='gbtree',max_depth=4,n_estimators=900,learning_rate=0.055)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 89.86%


/home/swethaudupa/shyam_works/new_project/walkin-campaigns/api/new_walkin/local/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [52]:
model.feature_importances_

array([0.2100329 , 0.14621711, 0.140625  , 0.03009868, 0.16842106,
       0.08470394, 0.        , 0.00246711, 0.00805921, 0.        ,
       0.01118421, 0.        , 0.02006579, 0.        , 0.00822368,
       0.00674342, 0.00444079, 0.        , 0.        , 0.00263158,
       0.00230263, 0.        , 0.00049342, 0.        , 0.00279605,
       0.        , 0.00296053, 0.00789474, 0.        , 0.00148026,
       0.        , 0.00197368, 0.00888158, 0.        , 0.        ,
       0.        , 0.02944079, 0.        , 0.06578948, 0.        ,
       0.01233553, 0.        , 0.00953947, 0.        , 0.01019737],
      dtype=float32)

In [74]:

a = pd.read_csv("train.csv")
ss = a.id

In [75]:
ss.dtype

dtype('int64')

In [ ]:
#sub1 = pd.DataFrame({'customerID':cluster_customers,'cluster':cluster_labels})

dat_fr = pd.DataFrame({'colum_name':data_set_one_hot.columns[1:],'import':model.feature_importances_})

In [54]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

In [55]:
confusion_matrix(y_test, predictions)


array([[58,  5],
       [ 9, 66]])

In [ ]:
from sklearn import linear_model, decomposition
compo = 30


pca = decomposition.PCA(n_components=compo)


pca.fit(X_train)

X_train_pca =pca.transform(X_train)

X_test_pca = pca.transform(X_test)


In [ ]:
sum(pca.explained_variance_ratio_)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_estimators=350,max_depth=4,criterion ='entropy', random_state=100)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(X_train, y_train)

# Apply the Classifier we trained to the test data (which, remember, it has never seen before)
pre = clf.predict(X_test)

#clf.predict_proba(test[features])[0:10]

accuracy = accuracy_score(y_test, pre)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

In [ ]:
confusion_matrix(y_test, pre)

In [ ]:
clf.feature_importances_

In [56]:
from sklearn import svm
from sklearn import preprocessing
le = preprocessing.StandardScaler()
le.fit(X_train)
X_train_sc  =le.transform(X_train)
X_test_sc =le.transform(X_test)
clf_svm = svm.SVC(C=1,gamma=.001)
clf_svm.fit(X_train_sc, y_train)  

pred_s = clf_svm.predict(X_test_sc)
accuracy = accuracy_score(y_test, pred_s)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 84.78%


In [57]:
confusion_matrix(y_test, pred_s)

array([[59,  4],
       [17, 58]])

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import GridSearchCV

from sklearn.svm import SVC

le1 = preprocessing.StandardScaler()
X_Sca = le1.fit_transform(X)

C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
param_grid = dict(gamma=gamma_range, C=C_range)
cv = StratifiedShuffleSplit(n_splits=5, test_size=0.3, random_state=42)
grid = GridSearchCV(SVC(), param_grid=param_grid, cv=cv)
grid.fit(X_Sca, Y)

print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))

In [ ]:
from sklearn.naive_bayes import GaussianNB

#le1 = preprocessing.StandardScaler()
#X_Sca = le1.fit_transform(X)

clf_nb = GaussianNB()
clf_nb.fit(X_train_sc, y_train)
target_pred = clf_nb.predict(X_test_sc)

accuracy = accuracy_score(y_test, target_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

In [ ]:
confusion_matrix(y_test, target_pred)

In [ ]:
test = pd.read_csv("test.csv")

In [ ]:
sub1 = pd.DataFrame({'id': X_test_al[:,0],'P' : y_test})

In [ ]:
sub1.to_csv('result.csv',index = False)

In [ ]:
from sklearn.preprocessing import LabelEncoder
hot_en = LabelEncoder()
#hot_en = LabelEncoder()
new_df = obj_df.apply(hot_en.fit_transform)
#new_df = obj_df.apply(hot_en.transform)
from sklearn.preprocessing import OneHotEncoder
one_hh = OneHotEncoder()
integer_encoded = hot_en.fit(data['G'])

In [ ]:
hot_en.classes_

In [ ]:
#test.G.fillna('NN',inplace =True)
#hot_en.transform(test['G'])

data.columns
X_1 = data[['A','C']]

In [ ]:
#hot_en = LabelEncoder()

#data.apply(hot_en.fit_transform)
hot_en.classes_

In [ ]:
from sklearn.preprocessing import CategoricalEncoder


In [ ]:
#obj_df = data.select_dtypes(include=['object']).copy()
#obj_df.head()
#test.drop(['D','J'],axis=1,inplace =True)
obj_df = test.select_dtypes(include=['object']).copy()
obj_df.head()

In [ ]:
test.B.fillna(28.17,inplace = True)
test.N.fillna(152,inplace = True)

test.fillna("NN",inplace = True)

In [ ]:
#hot_en = LabelEncoder()
new_df = obj_df.apply(hot_en.fit_transform)
#new_df = obj_df.apply(hot_en.transform)
from sklearn.preprocessing import OneHotEncoder
one_hh = OneHotEncoder()

In [ ]:
new_df.head()

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one_hh = OneHotEncoder()

In [ ]:
ss  =one_hh.fit_transform(new_df)

In [ ]:
type(ss)

In [ ]:
ss1  =one_hh.transform(new_df)

In [ ]:
type(ss1)

In [ ]:
ss1.shape

In [ ]:
ss.shape

In [ ]:
A =ss.toarray()

In [ ]:
obj_df_1 = test.select_dtypes(include=['float64','int64']).copy()
obj_df_1.head()

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

np.concatenate((a, b.T), axis=1)


array([[1, 2, 5],
       [3, 4, 6]])

In [44]:
data_int = data.select_dtypes(include=['float64','int64']).copy()
data_int.head()
data_cat = data.select_dtypes(include=['object']).copy()
data_int.head()
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encod = LabelEncoder()

data_cat_le = data_cat.apply(label_encod.fit_transform)

one_he = OneHotEncoder()
data_X =one_he.fit_transform(data_cat_le)
data_X =data_X.toarray()
data_int = data_int.as_matrix()
train_data = np.concatenate((data_int[:,1::],data_X ), axis=1)

In [45]:
train_data.shape

(552, 45)

In [17]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [3]:
ab = pd.read_csv("sampl.csv")

In [31]:
#l = LabelEncoder()
#l1 = LabelEncoder()
#ab["P_new"] = l.transform(ab["P"])
#ab["D_new"] = l1.transform(ab["D"])
obj_df_1 = ab.select_dtypes(include=['object']).copy()

In [32]:
A = obj_df_1.columns

In [33]:
for each in A:
    print each

P
D


In [34]:
dd ={}

In [35]:
for each in A:
    la = LabelEncoder().fit(obj_df_1[each])
    obj_df_1[each] = la.transform(obj_df_1[each])
   
    dd[each] = la
    

In [47]:
da = obj_df_1.as_matrix()


In [52]:
oe = OneHotEncoder().fit(da)


In [53]:
new_data = oe.transform(da)

In [55]:
new_data.toarray()

array([[1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [60]:
oe.n_values

'auto'

In [61]:
ss = pd.read_csv("sampl _rr.csv")

In [62]:
ss

id  P  D
0   1  a  a
1   2  a  a
2   3  b  a
3   4  c  a

In [63]:
obj_df_2 = ss.select_dtypes(include=['object']).copy()

In [64]:
B = obj_df_1.columns

In [65]:
for each in B:
    la = dd[each]
    obj_df_2[each] = la.transform(obj_df_2[each])
   


    

In [66]:
obj_df_2

P  D
0  0  0
1  0  0
2  1  0
3  2  0

In [67]:
sas =obj_df_2.as_matrix()

In [68]:
new_data1 = oe.transform(sas)

In [70]:
new_data.toarray()

array([[1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [71]:
new_data1.toarray()

array([[1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.]])